apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalproject
  labels:
    app: finalproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finalproject
  template:
    metadata:
      labels:
        app: finalproject
    spec:
      containers:
      - name: finalproject
        image: kamu9598/finalproject
        ports:
        - containerPort: 80